/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../app/routes/__root.tsx'
import { Route as PortalRouteImport } from './../../app/routes/portal.tsx'
import { Route as portalRouteRouteImport } from './../../app/routes/(portal)/route.tsx'
import { Route as guestRouteRouteImport } from './../../app/routes/(guest)/route.tsx'
import { Route as guestResetPasswordRouteImport } from './../../app/routes/(guest)/reset-password.tsx'
import { Route as guestLoginRouteImport } from './../../app/routes/(guest)/login.tsx'
import { Route as guestForgotPasswordRouteImport } from './../../app/routes/(guest)/forgot-password.tsx'
import { Route as errorsUnauthorizedRouteImport } from './../../app/routes/(errors)/unauthorized.tsx'
import { Route as portalStudentRouteRouteImport } from './../../app/routes/(portal)/student/route.tsx'
import { Route as portalAdminRouteRouteImport } from './../../app/routes/(portal)/admin/route.tsx'
import { Route as portalStudentIndexRouteImport } from './../../app/routes/(portal)/student/index.tsx'
import { Route as portalAdminIndexRouteImport } from './../../app/routes/(portal)/admin/index.tsx'
import { Route as portalAdminClassesIndexRouteImport } from './../../app/routes/(portal)/admin/classes/index.tsx'
import { Route as portalAdminClassesSlugRouteImport } from './../../app/routes/(portal)/admin/classes/$slug.tsx'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const portalRouteRoute = portalRouteRouteImport.update({
  id: '/(portal)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestRouteRoute = guestRouteRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestResetPasswordRoute = guestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => guestRouteRoute,
} as any)
const guestLoginRoute = guestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => guestRouteRoute,
} as any)
const guestForgotPasswordRoute = guestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => guestRouteRoute,
} as any)
const errorsUnauthorizedRoute = errorsUnauthorizedRouteImport.update({
  id: '/(errors)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const portalStudentRouteRoute = portalStudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => portalRouteRoute,
} as any)
const portalAdminRouteRoute = portalAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => portalRouteRoute,
} as any)
const portalStudentIndexRoute = portalStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => portalStudentRouteRoute,
} as any)
const portalAdminIndexRoute = portalAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => portalAdminRouteRoute,
} as any)
const portalAdminClassesIndexRoute = portalAdminClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => portalAdminRouteRoute,
} as any)
const portalAdminClassesSlugRoute = portalAdminClassesSlugRouteImport.update({
  id: '/classes/$slug',
  path: '/classes/$slug',
  getParentRoute: () => portalAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/portal': typeof PortalRoute
  '/admin': typeof portalAdminRouteRouteWithChildren
  '/student': typeof portalStudentRouteRouteWithChildren
  '/unauthorized': typeof errorsUnauthorizedRoute
  '/forgot-password': typeof guestForgotPasswordRoute
  '/login': typeof guestLoginRoute
  '/reset-password': typeof guestResetPasswordRoute
  '/admin/': typeof portalAdminIndexRoute
  '/student/': typeof portalStudentIndexRoute
  '/admin/classes/$slug': typeof portalAdminClassesSlugRoute
  '/admin/classes/': typeof portalAdminClassesIndexRoute
}
export interface FileRoutesByTo {
  '/portal': typeof PortalRoute
  '/unauthorized': typeof errorsUnauthorizedRoute
  '/forgot-password': typeof guestForgotPasswordRoute
  '/login': typeof guestLoginRoute
  '/reset-password': typeof guestResetPasswordRoute
  '/admin': typeof portalAdminIndexRoute
  '/student': typeof portalStudentIndexRoute
  '/admin/classes/$slug': typeof portalAdminClassesSlugRoute
  '/admin/classes': typeof portalAdminClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(guest)': typeof guestRouteRouteWithChildren
  '/(portal)': typeof portalRouteRouteWithChildren
  '/portal': typeof PortalRoute
  '/(portal)/admin': typeof portalAdminRouteRouteWithChildren
  '/(portal)/student': typeof portalStudentRouteRouteWithChildren
  '/(errors)/unauthorized': typeof errorsUnauthorizedRoute
  '/(guest)/forgot-password': typeof guestForgotPasswordRoute
  '/(guest)/login': typeof guestLoginRoute
  '/(guest)/reset-password': typeof guestResetPasswordRoute
  '/(portal)/admin/': typeof portalAdminIndexRoute
  '/(portal)/student/': typeof portalStudentIndexRoute
  '/(portal)/admin/classes/$slug': typeof portalAdminClassesSlugRoute
  '/(portal)/admin/classes/': typeof portalAdminClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/portal'
    | '/admin'
    | '/student'
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/'
    | '/student/'
    | '/admin/classes/$slug'
    | '/admin/classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/portal'
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/student'
    | '/admin/classes/$slug'
    | '/admin/classes'
  id:
    | '__root__'
    | '/(guest)'
    | '/(portal)'
    | '/portal'
    | '/(portal)/admin'
    | '/(portal)/student'
    | '/(errors)/unauthorized'
    | '/(guest)/forgot-password'
    | '/(guest)/login'
    | '/(guest)/reset-password'
    | '/(portal)/admin/'
    | '/(portal)/student/'
    | '/(portal)/admin/classes/$slug'
    | '/(portal)/admin/classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  guestRouteRoute: typeof guestRouteRouteWithChildren
  portalRouteRoute: typeof portalRouteRouteWithChildren
  PortalRoute: typeof PortalRoute
  errorsUnauthorizedRoute: typeof errorsUnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(portal)': {
      id: '/(portal)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof portalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/reset-password': {
      id: '/(guest)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof guestResetPasswordRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/(guest)/login': {
      id: '/(guest)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof guestLoginRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/(guest)/forgot-password': {
      id: '/(guest)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof guestForgotPasswordRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/(errors)/unauthorized': {
      id: '/(errors)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof errorsUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(portal)/student': {
      id: '/(portal)/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof portalStudentRouteRouteImport
      parentRoute: typeof portalRouteRoute
    }
    '/(portal)/admin': {
      id: '/(portal)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof portalAdminRouteRouteImport
      parentRoute: typeof portalRouteRoute
    }
    '/(portal)/student/': {
      id: '/(portal)/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof portalStudentIndexRouteImport
      parentRoute: typeof portalStudentRouteRoute
    }
    '/(portal)/admin/': {
      id: '/(portal)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof portalAdminIndexRouteImport
      parentRoute: typeof portalAdminRouteRoute
    }
    '/(portal)/admin/classes/': {
      id: '/(portal)/admin/classes/'
      path: '/classes'
      fullPath: '/admin/classes/'
      preLoaderRoute: typeof portalAdminClassesIndexRouteImport
      parentRoute: typeof portalAdminRouteRoute
    }
    '/(portal)/admin/classes/$slug': {
      id: '/(portal)/admin/classes/$slug'
      path: '/classes/$slug'
      fullPath: '/admin/classes/$slug'
      preLoaderRoute: typeof portalAdminClassesSlugRouteImport
      parentRoute: typeof portalAdminRouteRoute
    }
  }
}

interface guestRouteRouteChildren {
  guestForgotPasswordRoute: typeof guestForgotPasswordRoute
  guestLoginRoute: typeof guestLoginRoute
  guestResetPasswordRoute: typeof guestResetPasswordRoute
}

const guestRouteRouteChildren: guestRouteRouteChildren = {
  guestForgotPasswordRoute: guestForgotPasswordRoute,
  guestLoginRoute: guestLoginRoute,
  guestResetPasswordRoute: guestResetPasswordRoute,
}

const guestRouteRouteWithChildren = guestRouteRoute._addFileChildren(
  guestRouteRouteChildren,
)

interface portalAdminRouteRouteChildren {
  portalAdminIndexRoute: typeof portalAdminIndexRoute
  portalAdminClassesSlugRoute: typeof portalAdminClassesSlugRoute
  portalAdminClassesIndexRoute: typeof portalAdminClassesIndexRoute
}

const portalAdminRouteRouteChildren: portalAdminRouteRouteChildren = {
  portalAdminIndexRoute: portalAdminIndexRoute,
  portalAdminClassesSlugRoute: portalAdminClassesSlugRoute,
  portalAdminClassesIndexRoute: portalAdminClassesIndexRoute,
}

const portalAdminRouteRouteWithChildren =
  portalAdminRouteRoute._addFileChildren(portalAdminRouteRouteChildren)

interface portalStudentRouteRouteChildren {
  portalStudentIndexRoute: typeof portalStudentIndexRoute
}

const portalStudentRouteRouteChildren: portalStudentRouteRouteChildren = {
  portalStudentIndexRoute: portalStudentIndexRoute,
}

const portalStudentRouteRouteWithChildren =
  portalStudentRouteRoute._addFileChildren(portalStudentRouteRouteChildren)

interface portalRouteRouteChildren {
  portalAdminRouteRoute: typeof portalAdminRouteRouteWithChildren
  portalStudentRouteRoute: typeof portalStudentRouteRouteWithChildren
}

const portalRouteRouteChildren: portalRouteRouteChildren = {
  portalAdminRouteRoute: portalAdminRouteRouteWithChildren,
  portalStudentRouteRoute: portalStudentRouteRouteWithChildren,
}

const portalRouteRouteWithChildren = portalRouteRoute._addFileChildren(
  portalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  guestRouteRoute: guestRouteRouteWithChildren,
  portalRouteRoute: portalRouteRouteWithChildren,
  PortalRoute: PortalRoute,
  errorsUnauthorizedRoute: errorsUnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
