/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../app/routes/__root.tsx'
import { Route as ResetPasswordRouteImport } from './../../app/routes/reset-password.tsx'
import { Route as authenticatedRouteRouteImport } from './../../app/routes/(authenticated)/route.tsx'
import { Route as authenticatedIndexRouteImport } from './../../app/routes/(authenticated)/index.tsx'
import { Route as authLoginRouteImport } from './../../app/routes/(auth)/login.tsx'
import { Route as authForgetPasswordRouteImport } from './../../app/routes/(auth)/forget-password.tsx'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgetPasswordRoute = authForgetPasswordRouteImport.update({
  id: '/(auth)/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/reset-password': typeof ResetPasswordRoute
  '/forget-password': typeof authForgetPasswordRoute
  '/login': typeof authLoginRoute
  '/': typeof authenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/reset-password': typeof ResetPasswordRoute
  '/forget-password': typeof authForgetPasswordRoute
  '/login': typeof authLoginRoute
  '/': typeof authenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/(auth)/forget-password': typeof authForgetPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/reset-password' | '/forget-password' | '/login' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/reset-password' | '/forget-password' | '/login' | '/'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/reset-password'
    | '/(auth)/forget-password'
    | '/(auth)/login'
    | '/(authenticated)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  authForgetPasswordRoute: typeof authForgetPasswordRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forget-password': {
      id: '/(auth)/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof authForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedIndexRoute: typeof authenticatedIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedIndexRoute: authenticatedIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  authForgetPasswordRoute: authForgetPasswordRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
